# This tells Netlify where your public files are.
# The "." means the root directory.
[build]
  publish = "."

# This tells Netlify where your serverless functions are.
[functions]
  directory = "api/"
