# This tells Netlify where your public files are.
[build]
  publish = "."

# This tells Netlify where your serverless functions are.
[functions]
  directory = "api/"

  # Try to define a default timeout for all functions
  [functions.params]
    timeout = 26 # In seconds

# This is the new, important rule.
# It tells Netlify how to route requests to your function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
