# This tells Netlify where your public files are.
[build]
  publish = "."

# This tells Netlify where your serverless functions are.
[functions]
  directory = "api/"
  # Add the following line to increase the function timeout to 26 seconds (26000 ms)
  timeout = 26

# This is the new, important rule.
# It tells Netlify how to route requests to your function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
